<a href="https://colab.research.google.com/github/Tahan402/Tahan402/blob/Capstone/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


NumPy is a Linear Algebra Library for Python. 

All libraries use numpy as a base for building other libraries.
 
Numpy is also very fast


Import numpy as a library. np is a general convention


In [1]:
import numpy as np
import pandas as pd

#Numpy usage


* Using Numpy we can create vectors, arrays, matrices and generate random numbers.

* NumPy arrays essentially come in two types: vectors and matrices.

* Vectors are strictly 1-D arrays and matrices are 2-D arrays. They are a list or a list of lists

In [2]:
list1 = [25,20,58]
list1

[25, 20, 58]

In [3]:
np.array(list1)

array([25, 20, 58])

In [4]:
a =np.array([[12.0,5.0,8.0],[25.0,15.0,62.0]])
print(a)

[[12.  5.  8.]
 [25. 15. 62.]]


Get the dimension of 'a'

In [5]:
a.ndim # row is one dimension and column is another dimension

2

In [6]:
a.shape

(2, 3)

In [7]:
b = np.array(list1)

In [8]:
print(b)

[25 20 58]


In [9]:
b.ndim

1

In [10]:
b.shape

(3,)

In [11]:
c =np.array([[12.0,25.0,36.0],[52.0,65.0,24.0],[85.0,87.0,95.0],[78.0,56.0,23.0]])

In [12]:
print(c)

[[12. 25. 36.]
 [52. 65. 24.]
 [85. 87. 95.]
 [78. 56. 23.]]


In [13]:
c.ndim

2

In [14]:
c.shape

(4, 3)

In [15]:
d = np.array([[[100,25],[36,42]],[[56,85],[96,23]],[[56,96],[38,75]]])

In [16]:
print(d)

[[[100  25]
  [ 36  42]]

 [[ 56  85]
  [ 96  23]]

 [[ 56  96]
  [ 38  75]]]


In [17]:
d.ndim

3

In [18]:
d.shape

(3, 2, 2)

Finding the Datatype

In [19]:
b.dtype

dtype('int64')

Finding the size of an Array

In [20]:
a.itemsize #item size will be 8 because this array consists of integers and size of integers( in bytes) in 8 bytes

8

In [21]:
a.size #this is for getting number of items in an array 

6

In [22]:
b.size

3

In [23]:
a.nbytes # 6 items * 8 bytes each

48

In [24]:
b.nbytes

24

#Accessing/Changing specific elements, rows, columns, etc


In [33]:
a =  np.array([[1,5,6,8,7,9],[86,77,94,35,12,41]])

In [34]:
print(a)

[[ 1  5  6  8  7  9]
 [86 77 94 35 12 41]]


Get a specific element from [r*c] 

In [35]:
a[1,5]

41

In [36]:
a[0,4]

7

Get a specific row

In [37]:
a[0,:]

array([1, 5, 6, 8, 7, 9])

Get a specific column

In [38]:
a[:,1]

array([ 5, 77])

Getting into a bit more fancy operations [startindex:endindex:stepsize]


In [39]:
a[0,1: -1:2]

array([5, 8])

In [40]:
a[1,1:-1:3]

array([77, 12])

In [41]:
a[1,5]

41

Changing the elements in array

In [42]:
a[:,1] =[100,101]

In [43]:
a

array([[  1, 100,   6,   8,   7,   9],
       [ 86, 101,  94,  35,  12,  41]])

In [44]:
a[0,3]=111

In [45]:
a

array([[  1, 100,   6, 111,   7,   9],
       [ 86, 101,  94,  35,  12,  41]])

In [46]:
a[0,4:6] = 562

In [47]:
a

array([[  1, 100,   6, 111, 562, 562],
       [ 86, 101,  94,  35,  12,  41]])

In [48]:
a[0:1,4:6]=300

In [49]:
a

array([[  1, 100,   6, 111, 300, 300],
       [ 86, 101,  94,  35,  12,  41]])

In [51]:
a[0:2,4:6] = ([400,401],[250,251])

In [52]:
a

array([[  1, 100,   6, 111, 400, 401],
       [ 86, 101,  94,  35, 250, 251]])

In [53]:
a[0:,] = [500,501,502,503,504,505]

In [54]:
a

array([[500, 501, 502, 503, 504, 505],
       [500, 501, 502, 503, 504, 505]])

In [55]:
a[0,:] = [600,601,602,603,604,605]

In [56]:
a

array([[600, 601, 602, 603, 604, 605],
       [500, 501, 502, 503, 504, 505]])

Example of a 3D array

In [57]:
b1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [58]:
print(b1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Getting a specific value from a 3D Array (It is called work outside-in).


In [59]:
b1[0,1,1]

4

Explanation for b1[0,1,1]

* First we get the row which has index 0 i.e. [1,2],[3,4]
* Next we get the list(set) which has index 1 i.e. [3,4]
* Next we get the element in [3,4] which has index 1 i.e. 4

Replacing a value in 3D array


In [60]:
b1[:,1,:] =[[9,9],[11,13]]

In [61]:
b1

array([[[ 1,  2],
        [ 9,  9]],

       [[ 5,  6],
        [11, 13]]])