<a href="https://colab.research.google.com/github/Tahan402/Tahan402/blob/Capstone/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


NumPy is a Linear Algebra Library for Python. 

All libraries use numpy as a base for building other libraries.
 
Numpy is also very fast


Import numpy as a library. np is a general convention


In [1]:
import numpy as np
import pandas as pd

#Numpy usage


* Using Numpy we can create vectors, arrays, matrices and generate random numbers.

* NumPy arrays essentially come in two types: vectors and matrices.

* Vectors are strictly 1-D arrays and matrices are 2-D arrays. They are a list or a list of lists

In [2]:
list1 = [25,20,58]
list1

[25, 20, 58]

In [3]:
np.array(list1)

array([25, 20, 58])

In [4]:
a =np.array([[12.0,5.0,8.0],[25.0,15.0,62.0]])
print(a)

[[12.  5.  8.]
 [25. 15. 62.]]


Get the dimension of 'a'

In [6]:
a.ndim # row is one dimension and column is another dimension

2

In [7]:
a.shape

(2, 3)

In [8]:
b = np.array(list1)

In [10]:
print(b)

[25 20 58]


In [11]:
b.ndim

1

In [12]:
b.shape

(3,)

In [13]:
c =np.array([[12.0,25.0,36.0],[52.0,65.0,24.0],[85.0,87.0,95.0],[78.0,56.0,23.0]])

In [14]:
print(c)

[[12. 25. 36.]
 [52. 65. 24.]
 [85. 87. 95.]
 [78. 56. 23.]]


In [15]:
c.ndim

2

In [16]:
c.shape

(4, 3)

In [17]:
d = np.array([[[100,25],[36,42]],[[56,85],[96,23]],[[56,96],[38,75]]])

In [18]:
print(d)

[[[100  25]
  [ 36  42]]

 [[ 56  85]
  [ 96  23]]

 [[ 56  96]
  [ 38  75]]]


In [19]:
d.ndim

3

In [20]:
d.shape

(3, 2, 2)

Finding the Datatype

In [21]:
b.dtype

dtype('int64')

Finding the size of an Array

In [23]:
a.itemsize #item size will be 8 because this array consists of integers and size of integers( in bytes) in 8 bytes

8

In [24]:
a.size #this is for getting number of items in an array 

6

In [25]:
b.size

3

In [27]:
a.nbytes # 6 items * 8 bytes each

48

In [28]:
b.nbytes

24